### ISSUE TITLE
parent_of(@item) and children_of(@item) not working in nanoc 4.2.1

### ISSUE THREAD

**Issue by pmalik56** [nanoc/nanoc#874]
I was trying to upgrade my nanoc version from nanoc-3.7.5 to nanoc-4.2.1 .

I have followed the documentation but this parent_of(@item) and children_of(@item) seems not fetching any value where @item.parent and @item.children was fetching values in older nanoc version.
http://nanoc.ws/doc/nanoc-4-upgrade-guide/ point 5 and 6 followed.

Please let me know if there is any kind of configuration for this to work or it's a bug not sure?

Error Message --- >>>
Message:

NoMethodError: undefined method `[]' for nil:NilClass

===== STACK TRACE:

  0. layout /pages/aihe.erb:3:in `get_binding'
  1. /usr/local/lib/ruby/2.3.0/erb.rb:864:in `eval'
  2. /usr/local/lib/ruby/2.3.0/erb.rb:864:in `result'
  3. /usr/local/lib/ruby/gems/2.3.0/gems/nanoc-4.2.1/lib/nanoc/filters/erb.rb:32:in `run'
  4. /usr/local/lib/ruby/gems/2.3.0/gems/nanoc-4.2.1/lib/nanoc/base/compilation/filter.rb:130:in `setup_and_run'
  5. /usr/local/lib/ruby/gems/2.3.0/gems/nanoc-4.2.1/lib/nanoc/base/services/executor.rb:78:in `layout'
  6. /usr/local/lib/ruby/gems/2.3.0/gems/nanoc-4.2.1/lib/nanoc/base/compilation/compiler.rb:250:in `block in recalculate_content_for_rep'
  7. /usr/local/lib/ruby/gems/2.3.0/gems/nanoc-4.2.1/lib/nanoc/base/entities/rule_memory.rb:57:in `block in each'
  8. /usr/local/lib/ruby/gems/2.3.0/gems/nanoc-4.2.1/lib/nanoc/base/entities/rule_memory.rb:57:in `each'
  9. /usr/local/lib/ruby/gems/2.3.0/gems/nanoc-4.2.1/lib/nanoc/base/entities/rule_memory.rb:57:in `each'
  10. /usr/local/lib/ruby/gems/2.3.0/gems/nanoc-4.2.1/lib/nanoc/base/compilation/compiler.rb:245:in `recalculate_content_for_rep'
  11. /usr/local/lib/ruby/gems/2.3.0/gems/nanoc-4.2.1/lib/nanoc/base/compilation/compiler.rb:220:in `compile_rep'
  12. /usr/local/lib/ruby/gems/2.3.0/gems/nanoc-4.2.1/lib/nanoc/base/compilation/compiler.rb:193:in `block in compile_reps'
  13. /usr/local/lib/ruby/gems/2.3.0/gems/nanoc-4.2.1/lib/nanoc/base/services/item_rep_selector.rb:18:in `block in each'
  14. /usr/local/lib/ruby/gems/2.3.0/gems/nanoc-4.2.1/lib/nanoc/base/services/item_rep_selector.rb:13:in `loop'
  15. /usr/local/lib/ruby/gems/2.3.0/gems/nanoc-4.2.1/lib/nanoc/base/services/item_rep_selector.rb:13:in `each'
  16. /usr/local/lib/ruby/gems/2.3.0/gems/nanoc-4.2.1/lib/nanoc/base/compilation/compiler.rb:191:in `compile_reps'
  17. /usr/local/lib/ruby/gems/2.3.0/gems/nanoc-4.2.1/lib/nanoc/base/compilation/compiler.rb:89:in `run'
  18. /usr/local/lib/ruby/gems/2.3.0/gems/nanoc-4.2.1/lib/nanoc/base/compilation/compiler.rb:77:in `run_all'
  19. /usr/local/lib/ruby/gems/2.3.0/gems/nanoc-4.2.1/lib/nanoc/base/entities/site.rb:30:in `compile'
  20. /usr/local/lib/ruby/gems/2.3.0/gems/nanoc-4.2.1/lib/nanoc/cli/commands/compile.rb:367:in `block in run'
  21. /usr/local/lib/ruby/gems/2.3.0/gems/nanoc-4.2.1/lib/nanoc/cli/commands/compile.rb:409:in `run_listeners_while'
  22. /usr/local/lib/ruby/gems/2.3.0/gems/nanoc-4.2.1/lib/nanoc/cli/commands/compile.rb:366:in `run'
  23. /usr/local/lib/ruby/gems/2.3.0/gems/nanoc-4.2.1/lib/nanoc/cli/command_runner.rb:12:in `block in call'
  24. /usr/local/lib/ruby/gems/2.3.0/gems/nanoc-4.2.1/lib/nanoc/cli/error_handler.rb:64:in `handle_while'
  25. /usr/local/lib/ruby/gems/2.3.0/gems/nanoc-4.2.1/lib/nanoc/cli/error_handler.rb:22:in `handle_while'
  26. /usr/local/lib/ruby/gems/2.3.0/gems/nanoc-4.2.1/lib/nanoc/cli/command_runner.rb:11:in `call'
  27. /usr/local/lib/ruby/gems/2.3.0/gems/cri-2.7.0/lib/cri/command_dsl.rb:233:in `block in runner'
  28. /usr/local/lib/ruby/gems/2.3.0/gems/cri-2.7.0/lib/cri/command.rb:294:in `run_this'
  29. /usr/local/lib/ruby/gems/2.3.0/gems/cri-2.7.0/lib/cri/command.rb:247:in `run'
  30. /usr/local/lib/ruby/gems/2.3.0/gems/nanoc-4.2.1/lib/nanoc/cli/commands/nanoc.rb:37:in `block in define'
  31. /usr/local/lib/ruby/gems/2.3.0/gems/cri-2.7.0/lib/cri/command.rb:294:in `run_this'
  32. /usr/local/lib/ruby/gems/2.3.0/gems/cri-2.7.0/lib/cri/command.rb:247:in `run'
  33. /usr/local/lib/ruby/gems/2.3.0/gems/nanoc-4.2.1/lib/nanoc/cli.rb:53:in `block in run'
  34. /usr/local/lib/ruby/gems/2.3.0/gems/nanoc-4.2.1/lib/nanoc/cli/error_handler.rb:64:in `handle_while'
  35. /usr/local/lib/ruby/gems/2.3.0/gems/nanoc-4.2.1/lib/nanoc/cli/error_handler.rb:22:in `handle_while'
  36. /usr/local/lib/ruby/gems/2.3.0/gems/nanoc-4.2.1/lib/nanoc/cli.rb:51:in `run'
  37. /usr/local/lib/ruby/gems/2.3.0/gems/nanoc-4.2.1/bin/nanoc:9:in `<top (required)>'
  38. /usr/local/bin/nanoc:23:in `load'
  39. /usr/local/bin/nanoc:23:in `<top (required)>'
  40. /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `load'
  41. /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `kernel_load'
  42. /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:24:in `run'
  43. /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli.rb:304:in `exec'
  44. /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  45. /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  46. /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
  47. /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
  48. /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli.rb:11:in `start'
  49. /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/exe/bundle:27:in `block in <top (required)>'
  50. /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
  51. /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/exe/bundle:19:in `<top (required)>'
  52. /usr/local/bin/bundle:23:in `load'

===== VERSION INFORMATION:

Nanoc 4.2.1 © 2007-2016 Denis Defreyne.
Running ruby 2.3.1 (2016-04-26) on x86_64-linux with RubyGems 2.5.1.

===== SYSTEM INFORMATION:

Linux partha-elisa 4.2.0-38-generic #45~14.04.1-Ubuntu SMP Thu Jun 9 09:27:51 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

===== INSTALLED GEMS:

  adsf 1.2.0
  builder 3.2.2
  bundler 1.12.5
  coderay 1.1.1
  colored 1.2
  commonjs 0.2.7
  cri 2.7.0
  daemons 1.2.3
  diff-lcs 1.2.5
  eventmachine 1.2.0.1
  ffi 1.9.10
  formatador 0.2.5
  guard 2.14.0
  guard-nanoc 1.0.2
  json 1.8.3
  less 2.6.0
  libv8 3.16.14.15
  listen 3.1.5
  lumberjack 1.0.10
  method_source 0.8.2
  mime-types 2.6.1
  mini_portile 0.6.2
  nanoc 4.2.1
  nenv 0.3.0
  nokogiri 1.6.6.2
  notiffany 0.1.0
  pry 0.10.3
  rack 1.6.4
  rb-fsevent 0.9.7
  rb-inotify 0.9.7
  ref 2.0.0
  rspec 2.14.1
  rspec-core 2.14.8
  rspec-expectations 2.14.5
  rspec-mocks 2.14.6
  ruby_dep 1.3.1
  shellany 0.0.1
  slop 3.6.0
  therubyracer 0.12.2
  thin 1.6.3
  thor 0.19.1

===== LOAD PATHS:

  0. /usr/local/lib/ruby/gems/2.3.0/gems/ref-2.0.0/lib
  1. /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib
  2. /usr/local/lib/ruby/gems/2.3.0/gems/thin-1.6.3/lib
  3. /usr/local/lib/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0-static/thin-1.6.3
  4. /usr/local/lib/ruby/gems/2.3.0/gems/therubyracer-0.12.2/lib
  5. /usr/local/lib/ruby/gems/2.3.0/gems/therubyracer-0.12.2/ext
  6. /usr/local/lib/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0-static/therubyracer-0.12.2
  7. /usr/local/lib/ruby/gems/2.3.0/gems/rspec-2.14.1/lib
  8. /usr/local/lib/ruby/gems/2.3.0/gems/rspec-mocks-2.14.6/lib
  9. /usr/local/lib/ruby/gems/2.3.0/gems/rspec-expectations-2.14.5/lib
  10. /usr/local/lib/ruby/gems/2.3.0/gems/rspec-core-2.14.8/lib
  11. /usr/local/lib/ruby/gems/2.3.0/gems/ref-2.0.0/lib
  12. /usr/local/lib/ruby/gems/2.3.0/gems/nokogiri-1.6.6.2/lib
  13. /usr/local/lib/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0-static/nokogiri-1.6.6.2
  14. /usr/local/lib/ruby/gems/2.3.0/gems/mini_portile-0.6.2/lib
  15. /usr/local/lib/ruby/gems/2.3.0/gems/mime-types-2.6.1/lib
  16. /usr/local/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.15-x86_64-linux/lib
  17. /usr/local/lib/ruby/gems/2.3.0/gems/libv8-3.16.14.15-x86_64-linux/ext
  18. /usr/local/lib/ruby/gems/2.3.0/gems/less-2.6.0/lib
  19. /usr/local/lib/ruby/gems/2.3.0/gems/json-1.8.3/lib
  20. /usr/local/lib/ruby/gems/2.3.0/gems/guard-nanoc-1.0.2/lib
  21. /usr/local/lib/ruby/gems/2.3.0/gems/nanoc-4.2.1/lib
  22. /usr/local/lib/ruby/gems/2.3.0/gems/guard-2.14.0/lib
  23. /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib
  24. /usr/local/lib/ruby/gems/2.3.0/gems/pry-0.10.3/lib
  25. /usr/local/lib/ruby/gems/2.3.0/gems/slop-3.6.0/lib
  26. /usr/local/lib/ruby/gems/2.3.0/gems/method_source-0.8.2/lib
  27. /usr/local/lib/ruby/gems/2.3.0/gems/notiffany-0.1.0/lib
  28. /usr/local/lib/ruby/gems/2.3.0/gems/shellany-0.0.1/lib
  29. /usr/local/lib/ruby/gems/2.3.0/gems/nenv-0.3.0/lib
  30. /usr/local/lib/ruby/gems/2.3.0/gems/lumberjack-1.0.10/lib
  31. /usr/local/lib/ruby/gems/2.3.0/gems/listen-3.1.5/lib
  32. /usr/local/lib/ruby/gems/2.3.0/gems/ruby_dep-1.3.1/lib
  33. /usr/local/lib/ruby/gems/2.3.0/gems/rb-inotify-0.9.7/lib
  34. /usr/local/lib/ruby/gems/2.3.0/gems/rb-fsevent-0.9.7/lib
  35. /usr/local/lib/ruby/gems/2.3.0/gems/formatador-0.2.5/lib
  36. /usr/local/lib/ruby/gems/2.3.0/gems/ffi-1.9.10/lib
  37. /usr/local/lib/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0-static/ffi-1.9.10
  38. /usr/local/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib
  39. /usr/local/lib/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0-static/eventmachine-1.2.0.1
  40. /usr/local/lib/ruby/gems/2.3.0/gems/diff-lcs-1.2.5/lib
  41. /usr/local/lib/ruby/gems/2.3.0/gems/daemons-1.2.3/lib
  42. /usr/local/lib/ruby/gems/2.3.0/gems/cri-2.7.0/lib
  43. /usr/local/lib/ruby/gems/2.3.0/gems/commonjs-0.2.7/lib
  44. /usr/local/lib/ruby/gems/2.3.0/gems/colored-1.2/lib
  45. /usr/local/lib/ruby/gems/2.3.0/gems/coderay-1.1.1/lib
  46. /usr/local/lib/ruby/gems/2.3.0/gems/builder-3.2.2/lib
  47. /usr/local/lib/ruby/gems/2.3.0/gems/adsf-1.2.0/lib
  48. /usr/local/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib
  49. /usr/local/lib/ruby/site_ruby/2.3.0
  50. /usr/local/lib/ruby/site_ruby/2.3.0/x86_64-linux
  51. /usr/local/lib/ruby/site_ruby
  52. /usr/local/lib/ruby/vendor_ruby/2.3.0
  53. /usr/local/lib/ruby/vendor_ruby/2.3.0/x86_64-linux
  54. /usr/local/lib/ruby/vendor_ruby
  55. /usr/local/lib/ruby/2.3.0
  56. /usr/local/lib/ruby/2.3.0/x86_64-linux

**Comment by pmalik56** [comment]
I am using the old parent child folder structure as used for legacy type identifier.
And the folder structure can't be changed , is there any way to customize the parent_of function to get the parent item?

**Comment by ddfreyne** [comment]
@pmalik56 Is this issue resolved now? Haven’t had the tim to look into this yet.

**Comment by pmalik56** [comment]
I override these two method as I have different folder structure... so that way it's resolved.
