### ISSUE TITLE
Issue with updating from 4.0.2 to 4.1.2 - undefined method `path' 

### ISSUE THREAD

**Issue by igorspasic** [nanoc/nanoc#806]
[This site](https://github.com/heapspace/website) uses nanoc 4.0.2. When I upgrade to 4.1.2, the following error occurs:

```
NoMethodError: undefined method `path' for #<Nanoc::MutableItemView:0x007fd1520c5668>

Compilation stack:

  - [item]   /index.md (rep default)

Stack trace:

  0. /usr/local/lib/ruby/gems/2.2.0/gems/nanoc-4.1.2/lib/nanoc/helpers/link_to.rb:119:in `relative_path_to'
  1. layout /_events.html:4:in `block in get_binding'
  2. layout /_events.html:2:in `each'
  3. layout /_events.html:2:in `get_binding'
  4. /usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/erb.rb:863:in `eval'
  5. /usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/erb.rb:863:in `result'
  6. /usr/local/lib/ruby/gems/2.2.0/gems/nanoc-4.1.2/lib/nanoc/filters/erb.rb:32:in `run'
  7. /usr/local/lib/ruby/gems/2.2.0/gems/nanoc-4.1.2/lib/nanoc/base/compilation/filter.rb:130:in `setup_and_run'
  8. /usr/local/lib/ruby/gems/2.2.0/gems/nanoc-4.1.2/lib/nanoc/helpers/rendering.rb:119:in `render'
  9. layout /index.html:39:in `get_binding'
```

I figured that the issue is in `_event_small.html`:

```
<div class="item">
	<%=kind_icon(item[:kind])%>
	<div><%= link_to(h(item[:title]), item) %> : <%= h(item[:subtitle]) %></div>
	<div class="date"><%=datum(item[:event])%></div>
</div>
```

in using `link_to` - as you see, we pass `item` for `path` and in your code you call `item.path` - and for some reason, `path` is not defined?

Please help ;)

**Comment by ddfreyne** [comment]
Can you share the full stack trace? (Or share the `crash.log` file?)

`MutableItemView` is only used in the preprocessor, and during preprocessing, items don’t yet have paths, and thus `MutableItemView` does not have a `#path` method. If this crash occurs somewhere outside of the preprocessor, then that means `MutableItemView` is used when it shouldn’t, and that’d be a clear bug.

**Comment by igorspasic** [comment]
Hey @ddfreyne sure - Ive shared the whole site on github, so it is very easy to recreate.

`crash.log`

```

igor@SupraSurf:~/prj/heapspace/website:master$ cat crash.log                                                                                                                    ⏎ ✱ [23:44]
Crashlog created at 2016-01-22 23:44:38 +0100

===== MESSAGE:

NoMethodError: undefined method `path' for #<Nanoc::MutableItemView:0x007fd1520c5668>

===== COMPILATION STACK:

  - [item]   /index.md (rep default)

===== STACK TRACE:

  0. /usr/local/lib/ruby/gems/2.2.0/gems/nanoc-4.1.2/lib/nanoc/helpers/link_to.rb:119:in `relative_path_to'
  1. layout /_events.html:4:in `block in get_binding'
  2. layout /_events.html:2:in `each'
  3. layout /_events.html:2:in `get_binding'
  4. /usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/erb.rb:863:in `eval'
  5. /usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/erb.rb:863:in `result'
  6. /usr/local/lib/ruby/gems/2.2.0/gems/nanoc-4.1.2/lib/nanoc/filters/erb.rb:32:in `run'
  7. /usr/local/lib/ruby/gems/2.2.0/gems/nanoc-4.1.2/lib/nanoc/base/compilation/filter.rb:130:in `setup_and_run'
  8. /usr/local/lib/ruby/gems/2.2.0/gems/nanoc-4.1.2/lib/nanoc/helpers/rendering.rb:119:in `render'
  9. layout /index.html:39:in `get_binding'
  10. /usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/erb.rb:863:in `eval'
  11. /usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/erb.rb:863:in `result'
  12. /usr/local/lib/ruby/gems/2.2.0/gems/nanoc-4.1.2/lib/nanoc/filters/erb.rb:32:in `run'
  13. /usr/local/lib/ruby/gems/2.2.0/gems/nanoc-4.1.2/lib/nanoc/base/compilation/filter.rb:130:in `setup_and_run'
  14. /usr/local/lib/ruby/gems/2.2.0/gems/nanoc-4.1.2/lib/nanoc/base/services/executor.rb:91:in `layout'
  15. /usr/local/lib/ruby/gems/2.2.0/gems/nanoc-4.1.2/lib/nanoc/base/compilation/compiler.rb:257:in `block in recalculate_content_for_rep'
  16. /usr/local/lib/ruby/gems/2.2.0/gems/nanoc-4.1.2/lib/nanoc/base/entities/rule_memory.rb:44:in `block in each'
  17. /usr/local/lib/ruby/gems/2.2.0/gems/nanoc-4.1.2/lib/nanoc/base/entities/rule_memory.rb:44:in `each'
  18. /usr/local/lib/ruby/gems/2.2.0/gems/nanoc-4.1.2/lib/nanoc/base/entities/rule_memory.rb:44:in `each'
  19. /usr/local/lib/ruby/gems/2.2.0/gems/nanoc-4.1.2/lib/nanoc/base/compilation/compiler.rb:252:in `recalculate_content_for_rep'
  20. /usr/local/lib/ruby/gems/2.2.0/gems/nanoc-4.1.2/lib/nanoc/base/compilation/compiler.rb:227:in `compile_rep'
  21. /usr/local/lib/ruby/gems/2.2.0/gems/nanoc-4.1.2/lib/nanoc/base/compilation/compiler.rb:202:in `block in compile_reps'
  22. /usr/local/lib/ruby/gems/2.2.0/gems/nanoc-4.1.2/lib/nanoc/base/services/item_rep_selector.rb:18:in `block in each'
  23. /usr/local/lib/ruby/gems/2.2.0/gems/nanoc-4.1.2/lib/nanoc/base/services/item_rep_selector.rb:13:in `loop'
  24. /usr/local/lib/ruby/gems/2.2.0/gems/nanoc-4.1.2/lib/nanoc/base/services/item_rep_selector.rb:13:in `each'
  25. /usr/local/lib/ruby/gems/2.2.0/gems/nanoc-4.1.2/lib/nanoc/base/compilation/compiler.rb:200:in `compile_reps'
  26. /usr/local/lib/ruby/gems/2.2.0/gems/nanoc-4.1.2/lib/nanoc/base/compilation/compiler.rb:103:in `block in run'
  27. /usr/local/lib/ruby/gems/2.2.0/gems/nanoc-4.1.2/lib/nanoc/base/compilation/dependency_tracker.rb:18:in `run'
  28. /usr/local/lib/ruby/gems/2.2.0/gems/nanoc-4.1.2/lib/nanoc/base/compilation/compiler.rb:102:in `run'
  29. /usr/local/lib/ruby/gems/2.2.0/gems/nanoc-4.1.2/lib/nanoc/base/compilation/compiler.rb:89:in `run_all'
  30. /usr/local/lib/ruby/gems/2.2.0/gems/nanoc-4.1.2/lib/nanoc/base/entities/site.rb:24:in `compile'
  31. /usr/local/lib/ruby/gems/2.2.0/gems/nanoc-4.1.2/lib/nanoc/cli/commands/compile.rb:375:in `block in run'
  32. /usr/local/lib/ruby/gems/2.2.0/gems/nanoc-4.1.2/lib/nanoc/cli/commands/compile.rb:417:in `run_listeners_while'
  33. /usr/local/lib/ruby/gems/2.2.0/gems/nanoc-4.1.2/lib/nanoc/cli/commands/compile.rb:374:in `run'
  34. /usr/local/lib/ruby/gems/2.2.0/gems/nanoc-4.1.2/lib/nanoc/cli/command_runner.rb:12:in `block in call'
  35. /usr/local/lib/ruby/gems/2.2.0/gems/nanoc-4.1.2/lib/nanoc/cli/error_handler.rb:64:in `handle_while'
  36. /usr/local/lib/ruby/gems/2.2.0/gems/nanoc-4.1.2/lib/nanoc/cli/error_handler.rb:22:in `handle_while'
  37. /usr/local/lib/ruby/gems/2.2.0/gems/nanoc-4.1.2/lib/nanoc/cli/command_runner.rb:11:in `call'
  38. /usr/local/lib/ruby/gems/2.2.0/gems/cri-2.7.0/lib/cri/command_dsl.rb:233:in `block in runner'
  39. /usr/local/lib/ruby/gems/2.2.0/gems/cri-2.7.0/lib/cri/command.rb:294:in `call'
  40. /usr/local/lib/ruby/gems/2.2.0/gems/cri-2.7.0/lib/cri/command.rb:294:in `run_this'
  41. /usr/local/lib/ruby/gems/2.2.0/gems/cri-2.7.0/lib/cri/command.rb:247:in `run'
  42. /usr/local/lib/ruby/gems/2.2.0/gems/cri-2.7.0/lib/cri/command.rb:260:in `run'
  43. /usr/local/lib/ruby/gems/2.2.0/gems/nanoc-4.1.2/lib/nanoc/cli.rb:53:in `block in run'
  44. /usr/local/lib/ruby/gems/2.2.0/gems/nanoc-4.1.2/lib/nanoc/cli/error_handler.rb:64:in `handle_while'
  45. /usr/local/lib/ruby/gems/2.2.0/gems/nanoc-4.1.2/lib/nanoc/cli/error_handler.rb:22:in `handle_while'
  46. /usr/local/lib/ruby/gems/2.2.0/gems/nanoc-4.1.2/lib/nanoc/cli.rb:51:in `run'
  47. /usr/local/lib/ruby/gems/2.2.0/gems/nanoc-4.1.2/bin/nanoc:9:in `<top (required)>'
  48. /usr/local/lib/ruby/gems/2.2.0/bin/nanoc:23:in `load'

===== VERSION INFORMATION:

Nanoc 4.1.2 © 2007-2016 Denis Defreyne.
Running ruby 2.2.2 (2015-04-13) on x86_64-darwin14 with RubyGems 2.4.5.

===== SYSTEM INFORMATION:

Darwin SupraSurf.local 15.3.0 Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64 x86_64

===== INSTALLED GEMS:

  adsf 1.2.0
  builder 3.2.2
  bundler 1.11.0
  chunky_png 1.3.5
  coderay 1.1.0
  colored 1.2
  compass 1.0.3
  compass-core 1.0.3
  compass-import-once 1.0.5
  configure-s3-website 1.7.1
  cri 2.7.0
  deep_merge 1.0.0
  dotenv 1.0.2
  ffi 1.9.10
  formatador 0.2.5
  guard 2.13.0
  guard-compat 1.2.1
  guard-nanoc 2.0.0
  haml 4.0.7
  htmlcompressor 0.3.0
  jsmin 1.0.1
  json 1.8.3
  kramdown 1.9.0
  listen 3.0.5
  lumberjack 1.0.9
  method_source 0.8.2
  mime-types 3.0
  mime-types-data 3.2015.1120
  mini_portile2 2.0.0
  multi_json 1.11.2
  nanoc 4.1.2
  nanoc-external 1.0.1
  nenv 0.2.0
  nokogiri 1.6.7
  notiffany 0.0.8
  pry 0.10.3
  rack 1.6.4
  rainpress 1.0
  rb-fsevent 0.9.6
  rb-inotify 0.9.5
  s3_website 2.12.2
  sass 3.4.20
  shellany 0.0.1
  slop 3.6.0
  thor 0.19.1
  tilt 2.0.1

===== GEMFILE.LOCK:

GIT
  remote: git://github.com/nanoc/nanoc-external.git
  revision: e8efcfa2c2075222caa31a738280da4147b33f09
  branch: nanoc4
  specs:
    nanoc-external (1.0.1)
      nanoc (>= 3.8.0, < 5.0.0)

GEM
  remote: https://rubygems.org/
  specs:
    adsf (1.2.0)
      rack (>= 1.0.0)
    builder (3.2.2)
    chunky_png (1.3.5)
    coderay (1.1.0)
    colored (1.2)
    compass (1.0.3)
      chunky_png (~> 1.2)
      compass-core (~> 1.0.2)
      compass-import-once (~> 1.0.5)
      rb-fsevent (>= 0.9.3)
      rb-inotify (>= 0.9)
      sass (>= 3.3.13, < 3.5)
    compass-core (1.0.3)
      multi_json (~> 1.0)
      sass (>= 3.3.0, < 3.5)
    compass-import-once (1.0.5)
      sass (>= 3.2, < 3.5)
    configure-s3-website (1.7.1)
      deep_merge (= 1.0.0)
    cri (2.7.0)
      colored (~> 1.2)
    deep_merge (1.0.0)
    dotenv (1.0.2)
    ffi (1.9.10)
    formatador (0.2.5)
    guard (2.13.0)
      formatador (>= 0.2.4)
      listen (>= 2.7, <= 4.0)
      lumberjack (~> 1.0)
      nenv (~> 0.1)
      notiffany (~> 0.0)
      pry (>= 0.9.12)
      shellany (~> 0.0)
      thor (>= 0.18.1)
    guard-compat (1.2.1)
    guard-nanoc (2.0.0)
      guard (~> 2.8)
      guard-compat (~> 1.0)
      nanoc (~> 4.0)
    haml (4.0.7)
      tilt
    htmlcompressor (0.3.0)
    jsmin (1.0.1)
    json (1.8.3)
    kramdown (1.9.0)
    listen (3.0.5)
      rb-fsevent (>= 0.9.3)
      rb-inotify (>= 0.9)
    lumberjack (1.0.9)
    method_source (0.8.2)
    mime-types (3.0)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2015.1120)
    mini_portile2 (2.0.0)
    multi_json (1.11.2)
    nanoc (4.1.2)
      cri (~> 2.3)
    nenv (0.2.0)
    nokogiri (1.6.7)
      mini_portile2 (~> 2.0.0.rc2)
    notiffany (0.0.8)
      nenv (~> 0.1)
      shellany (~> 0.0)
    pry (0.10.3)
      coderay (~> 1.1.0)
      method_source (~> 0.8.1)
      slop (~> 3.4)
    rack (1.6.4)
    rainpress (1.0)
    rb-fsevent (0.9.6)
    rb-inotify (0.9.5)
      ffi (>= 0.5.0)
    s3_website (2.12.2)
      colored (= 1.2)
      configure-s3-website (= 1.7.1)
      dotenv (~> 1.0)
      thor (~> 0.18)
    sass (3.4.20)
    shellany (0.0.1)
    slop (3.6.0)
    thor (0.19.1)
    tilt (2.0.1)

PLATFORMS
  ruby

DEPENDENCIES
  adsf
  builder
  coderay
  compass
  guard-nanoc
  haml
  htmlcompressor
  jsmin
  json
  kramdown
  mime-types
  nanoc (= 4.1.2)
  nanoc-external!
  nokogiri
  rainpress
  s3_website
  sass

BUNDLED WITH
   1.11.0

===== LOAD PATHS:

  0. /usr/local/lib/ruby/gems/2.2.0/gems/s3_website-2.12.2/lib
  1. /usr/local/lib/ruby/gems/2.2.0/gems/rainpress-1.0/lib
  2. /usr/local/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-14/2.2.0/nokogiri-1.6.7
  3. /usr/local/lib/ruby/gems/2.2.0/gems/nokogiri-1.6.7/lib
  4. /usr/local/lib/ruby/gems/2.2.0/bundler/gems/nanoc-external-e8efcfa2c207/lib
  5. /usr/local/lib/ruby/gems/2.2.0/gems/mini_portile2-2.0.0/lib
  6. /usr/local/lib/ruby/gems/2.2.0/gems/mime-types-3.0/lib
  7. /usr/local/lib/ruby/gems/2.2.0/gems/mime-types-data-3.2015.1120/lib
  8. /usr/local/lib/ruby/gems/2.2.0/gems/kramdown-1.9.0/lib
  9. /usr/local/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-14/2.2.0/json-1.8.3
  10. /usr/local/lib/ruby/gems/2.2.0/gems/json-1.8.3/lib
  11. /usr/local/lib/ruby/gems/2.2.0/gems/jsmin-1.0.1/lib
  12. /usr/local/lib/ruby/gems/2.2.0/gems/htmlcompressor-0.3.0/lib
  13. /usr/local/lib/ruby/gems/2.2.0/gems/haml-4.0.7/lib
  14. /usr/local/lib/ruby/gems/2.2.0/gems/tilt-2.0.1/lib
  15. /usr/local/lib/ruby/gems/2.2.0/gems/guard-nanoc-2.0.0/lib
  16. /usr/local/lib/ruby/gems/2.2.0/gems/nanoc-4.1.2/lib
  17. /usr/local/lib/ruby/gems/2.2.0/gems/guard-compat-1.2.1/lib
  18. /usr/local/lib/ruby/gems/2.2.0/gems/guard-2.13.0/lib
  19. /usr/local/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib
  20. /usr/local/lib/ruby/gems/2.2.0/gems/pry-0.10.3/lib
  21. /usr/local/lib/ruby/gems/2.2.0/gems/slop-3.6.0/lib
  22. /usr/local/lib/ruby/gems/2.2.0/gems/method_source-0.8.2/lib
  23. /usr/local/lib/ruby/gems/2.2.0/gems/notiffany-0.0.8/lib
  24. /usr/local/lib/ruby/gems/2.2.0/gems/shellany-0.0.1/lib
  25. /usr/local/lib/ruby/gems/2.2.0/gems/nenv-0.2.0/lib
  26. /usr/local/lib/ruby/gems/2.2.0/gems/lumberjack-1.0.9/lib
  27. /usr/local/lib/ruby/gems/2.2.0/gems/listen-3.0.5/lib
  28. /usr/local/lib/ruby/gems/2.2.0/gems/formatador-0.2.5/lib
  29. /usr/local/lib/ruby/gems/2.2.0/gems/dotenv-1.0.2/lib
  30. /usr/local/lib/ruby/gems/2.2.0/gems/cri-2.7.0/lib
  31. /usr/local/lib/ruby/gems/2.2.0/gems/configure-s3-website-1.7.1/lib
  32. /usr/local/lib/ruby/gems/2.2.0/gems/deep_merge-1.0.0/lib
  33. /usr/local/lib/ruby/gems/2.2.0/gems/compass-1.0.3/lib
  34. /usr/local/lib/ruby/gems/2.2.0/gems/rb-inotify-0.9.5/lib
  35. /usr/local/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-14/2.2.0/ffi-1.9.10
  36. /usr/local/lib/ruby/gems/2.2.0/gems/ffi-1.9.10/lib
  37. /usr/local/lib/ruby/gems/2.2.0/gems/rb-fsevent-0.9.6/lib
  38. /usr/local/lib/ruby/gems/2.2.0/gems/compass-import-once-1.0.5/lib
  39. /usr/local/lib/ruby/gems/2.2.0/gems/compass-core-1.0.3/lib
  40. /usr/local/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib
  41. /usr/local/lib/ruby/gems/2.2.0/gems/multi_json-1.11.2/lib
  42. /usr/local/lib/ruby/gems/2.2.0/gems/colored-1.2/lib
  43. /usr/local/lib/ruby/gems/2.2.0/gems/coderay-1.1.0/lib
  44. /usr/local/lib/ruby/gems/2.2.0/gems/chunky_png-1.3.5/lib
  45. /usr/local/lib/ruby/gems/2.2.0/gems/builder-3.2.2/lib
  46. /usr/local/lib/ruby/gems/2.2.0/gems/adsf-1.2.0/lib
  47. /usr/local/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib
  48. /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.11.0/lib
  49. /usr/local/lib/ruby/site_ruby/2.2.0
  50. /usr/local/lib/ruby/site_ruby/2.2.0/x86_64-darwin14
  51. /usr/local/lib/ruby/site_ruby
  52. /usr/local/lib/ruby/vendor_ruby/2.2.0
  53. /usr/local/lib/ruby/vendor_ruby/2.2.0/x86_64-darwin14
  54. /usr/local/lib/ruby/vendor_ruby
  55. /usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0
  56. /usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/x86_64-darwin14

```

**Comment by igorspasic** [comment]
Im using `link_to(h(item[:title]), item)` on html partial.

**Comment by ddfreyne** [comment]
Can you share the `Rules`, `layouts/_events.html` and `layouts/index.html` files?

**Comment by igorspasic** [comment]
Hey @ddfreyne, everything is already shared - please check the very first link.

https://github.com/heapspace/website

**Comment by igorspasic** [comment]
Just checked 4.1.0; same thing.

**Comment by ddfreyne** [comment]
The problem arises from storing items during preprocessing in global variables (e.g. `$new_events`, `$old_events`). This stores the (mutable) item views, and during preprocessing, these will still be mutable views that don’t have a path.

I recommend not storing the items (or their views) in a global array, but store their identifiers instead, and fetch the appropriate item with `@items[identifier]` when needed.

(The use of global variables also bypasses Nanoc’s dependency tracking mechanism, and so I recommend not using globals at all—otherwise, you’ll end up having to `rm -rf tmp` before compiling for the compiled site to be correct.)

**Comment by igorspasic** [comment]
>  but store their identifiers instead

Sorry, i was not aware of this. What is identifier of an `item`?

**Comment by ddfreyne** [comment]
The [identifier](http://nanoc.ws/doc/identifiers-and-patterns/) of an item is their path, e.g. `/projects/nanoc.md`, and you can obtain it by calling `#identifier`.

**Comment by igorspasic** [comment]
Thanx! I will refactor my code.

**Comment by igorspasic** [comment]
Can I use `item.identifier`? I mean, how to get the identifier from the item?

**Comment by ddfreyne** [comment]
Yes: `item.identifier` is the identifier of the item.

**Comment by igorspasic** [comment]
Thank you very much. nanoc4 is my favorite weapon :)

**Comment by igorspasic** [comment]
Ok, one question - if you still watching this :)

I want to 'attach' additional information to each item. If I am not storing the mutable items (from preprocessing phase) - when and how I can 'bind' this information to items?

Example: I want to attach parsed date to each item.

Should I create separate memory structure for this and store it in the hash map, that has item identifiers as key?

**Comment by ddfreyne** [comment]
You can set attributes of an item with `#[]=`, e.g. `item[:title] = 'Donkey'`, and fetch it like `item[:title]`. Try to store all information on either items or the site configuration, so that Nanoc’s dependency tracker can do its thing.

**Comment by igorspasic** [comment]
Thanx! Already doing so. Awesome
