### ISSUE TITLE
NoMethodError: undefined method `synchronize' for nil:NilClass with 3.4.1

### ISSUE THREAD

**Issue by zmanji** [nanoc/nanoc#162]
I have recently upgraded to nanoc 3.4.1 and I am unable to compile my site. I am now obtaining the following error `NoMethodError: undefined method `synchronize' for nil:NilClass` with a [crash.log](https://gist.github.com/3869492).

The compilation seems to always fail when processing my LaTeX filter which worked fine with nanoc 3.4.0. The filter can be seen [here](https://github.com/zmanji/zameermanji.com/blob/4f97803dce690f5c354cdde4c6133fea7b526053/lib/filters/latex.rb).

I'm not sure why nanoc is failing to work with my filter now.
