### ISSUE TITLE
nanoc guard no longer works with nanoc version 4.11.13

### ISSUE THREAD

**Issue by Fjan** [nanoc/nanoc#1462]
It looks like Guard nanoc is accessing a method in nanoc that has been renamed. Downgrading to nanoc version 4.11.12 fixes the problem.

### Steps to reproduce

1.  Use Nanoc  4.11.13, guard-nanoc 2.1.6 and guard 2.16.1
2. `bundle exec guard`

### Expected behavior

Guard Nanoc starts

### Actual behavior

It fails to start

### Crash log

```
ERROR - Guard::Nanoc failed to achieve its <start>, exception was:
> [#3d60f37ee03b] NoMethodError: undefined method `load_command_at' for Nanoc::CLI:Module
> [#3d60f37ee03b] Did you mean?  load_commands_at
<snip>
Guard::Nanoc has just been fired
```

**Comment by josepegea** [comment]
Happens to me, too. Same error. Also fixed by downgrading to 4.11.12

**Comment by ddfreyne** [comment]
I fixed this issue, but forgot to release `guard-nanoc` with the fix! A fix is coming up shortly.

**Comment by ddfreyne** [comment]
Upgrade to guard-nanoc 2.1.7, and the problem should be gone.
