### ISSUE TITLE
Missing files in gem?

### ISSUE THREAD

**Issue by gjtorikian** [nanoc/nanoc#727]
This has been driving me crazy as a "No, couldn't be...could it?" situation. But it looks like there are files in this repo that are not present in the built gem.

For example, I've been looking for `ItemRepRepo`, but couldn't instantiate it for some reason. It looks like the gem I have installed does not match the one in the repo:

![image 2015-11-13 at 3 45 06 pm](https://cloud.githubusercontent.com/assets/64050/11160353/88c45fec-8a1d-11e5-849f-e6ccb9a37a25.png)

I don't know how this gem was packaged and distributed—it doesn't look like it was using the Bundler gem tasks, given the lack of these in the Rakefile—but I'm pretty sure something wasn't wrapped up correctly. This is for nanoc 4.0.0.

**Comment by gjtorikian** [comment]
Hm. Maybe `ItemRepRepo` isn't meant to be in the gem? In that case, how does one add a new rep to an existing item?

**Comment by ddfreyne** [comment]
`ItemRepRepo` is new in Nanoc 4.1.

In 4.0, `Nanoc::Int::Item` has `#reps`, an array of `Nanoc::Int::ItemRep`s, and adding a new repo can be done by appending to it:

```
item.reps << Nanoc::Int::ItemRep.new(item, :json)
```

Usually, the reps are generated automatically based on the `Rules` file. Hope this helps!

**Comment by gjtorikian** [comment]
Doh. Super clear. Sorry! I was looking for more documentation in reps and could only find the test cases as clear examples.

**Comment by ddfreyne** [comment]
I guess the lacking documentation is what nanoc/nanoc.ws#116 is for. :)

**Comment by gjtorikian** [comment]
Looks like `item.reps <<` is forbidden:

```
NoMethodError: undefined method `<<' for #<Nanoc::ItemRepCollectionView:0x007fd7961c36d8>
```

I only see that method defined for `ItemRepRepo`, which is probably where I got my first idea to use it from.

**Comment by ddfreyne** [comment]
`item.reps << x` won’t work on 4.1; on 4.1, you can modify `ItemRepRepo`.

(The reason why `ItemRepRepo` exists is so that at some point in a future version of nanoc, not all the item reps (nor items) will need to be in-memory anymore. That should reduce memory pressure and make nanoc capable of handling sites with tens of thousands of pages/assets.)

**Comment by gjtorikian** [comment]
It sounds like instead of doing this in 4.0, I should just wait patiently for 4.1 :D If I can't modify `item.reps` in 4.0, and `ItemRepRepo` does not yet exist, I simply don't see a way to modify the reps. :worried:

**Comment by ddfreyne** [comment]
@gjtorikian Nanoc 4.1 will be backwards compatible with 4.0, and I’d recommend making modifications in 4.1 rather than 4.0! There’s no release timeframe for 4.1, but I’ll try to release more often than with 3.x (where I averaged one minor release per year or so).
