### ISSUE TITLE
Compile crashes with DDMetrics::Stopwatch::AlreadyRunningError

### ISSUE THREAD

**Issue by sarahg** [nanoc/nanoc#1631]
### Steps to reproduce

I suspect this has something to do with the size of our project (docs.gitlab.com), so this might not be reproducible for everyone, but I can consistently reproduce the problem like this:

1. Clone the [gitlab-docs project](https://gitlab.com/gitlab-org/gitlab-docs) and install dependencies
2. Run `bundle exec nanoc compile`
3. Run `bundle exec nanoc compile` again
4. The compile crashes with this error:

```
/Users/sarahg/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/ddmetrics-1.0.1/lib/ddmetrics/stopwatch.rb:29:in `start': Cannot start, because stopwatch is already running (DDMetrics::Stopwatch::AlreadyRunningError)
```

### Expected behavior

Nanoc does not crash and completes the compile without errors.

### Actual behavior

Compile crashes before completion, 100% of the time.

### Details

- We have 1,907 total pages currently, and nanoc crashes after updating 1,424 files every time. If I remove the file it crashes on, it will crash on the next one, throwing the same error.
- Nanoc does **not** crash on the `create` operation, so a workaround has been to do a `rm -rf public && bundle exec nanoc compile`.

I can reproduce consistently on two different laptops (both m1 macs). My colleague @axilleas cannot reproduce on his Linux laptop. We have not seen this on CI pipelines, but we're always doing a fresh install there.

@axilleas reported a similar issue a few years ago, which was resolved: https://github.com/nanoc/nanoc/issues/1445

This seems to have been introduced when we upgraded from 4.12.10 to 4.12.12.

### Crash log

https://gitlab.com/-/snippets/2462123/raw/main/snippetfile1.txt

**Comment by denisdefreyne** [comment]
I’ve got a fix for the `undefined method 'closed?'` in #1632. I suspect that it’s hiding some other details that could help debug this properly.

**Comment by sarahg** [comment]
@denisdefreyne Thanks for taking a look! I updated my local copy following your directions from [over here](https://github.com/nanoc/nanoc/issues/1445#issuecomment-525607877) to get your last commit, and I see something new (in red here):

<img width="1351" alt="image" src="https://user-images.githubusercontent.com/667501/204615115-840b2f77-2ffb-40a3-8366-9bd92c433845.png">

This:
```
bundler: failed to load command: nanoc (/Users/sarahg/.asdf/installs/ruby/2.7.7/lib/ruby/gems/2.7.0/bin/nanoc)
```

Here's a gist that includes the full trace: https://gist.github.com/sarahg/2f5eaa1e0d0e5d6bf3c4f8e9c9b174e0#file-gistfile1-txt-L864

**Comment by denisdefreyne** [comment]
I can reproduce the issue!

**Comment by denisdefreyne** [comment]
Possible fix: #1633

**Comment by denisdefreyne** [comment]
@sarahg Would you be able to test out the fix in #1633 and let me know how it works?

With this fix, I can no longer reproduce the issue, but I’ve also been unable to reproduce it reliably in the first place…

**Comment by sarahg** [comment]
@denisdefreyne It works! I can no longer reproduce either, and I was seeing it 100% of the time. Having this working again made my day. 😄 Thank you for the quick fix!

**Comment by denisdefreyne** [comment]
This is now fixed in the Nanoc 4.12.13 release.
